### PR TITLE
Extract the phone number trough the xml __toString method.

### PR DESCRIPTION
**Pull request by itay9001**

### CODE REVIEW

**Comment by DivineOmega** [comment]
Hi there! Thanks for the contribution. May I ask what problem this fixes?

**Comment by itay9001** [comment]
Ofcourse, sorry for the lack of information.
It seem that during the extract of the phone number from getAll () method,
the phoneNumber field returnes false.
short workaround as this seems to fix it.

**Comment by DivineOmega** [comment]
Alright, thanks.

The phone number should appear in the e164 attribute. I would guess the phone number you are trying to read does not match the E.164 format perhaps, and Google is therefore not including it.

https://en.wikipedia.org/wiki/E.164

Would you mind seeing if this is the case in the contact(s) you're testing with?

**Comment by DivineOmega** [comment]
Regardless, this is worth merging, but I'd be very curious to find out why your contact phone numbers are not coming through in the e164 attribute.

**Pull request merged**
